### ISSUE TITLE
Need an Option to Stop Service from Dart Code.

### ISSUE THREAD

**Issue by canewsin** [ekasetiawans/flutter_background_service#10]
Helpful to manually stop service.

**Comment by canewsin** [comment]
@ekasetiawans

**Comment by ekasetiawans** [comment]
Currently, there is no channel method available to kill a service that is already running.

on Android we can call stopSelf in the service class, but care must be taken to deactivate the alarm service first so that the service does not wake up again.

reference: https://developer.android.com/reference/android/app/Service#stopSelf(int)

contributors are very welcome
