### ISSUE TITLE
(Android) how to use the camera while the app is in foreground/background

### ISSUE THREAD

**Issue by X-SLAYER** [ekasetiawans/flutter_background_service#122]
is it possible to use the camera while the app is in the foreground or background? 
 i always get this error message once i start the camera stream in the onStart() of back ground 
 `Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)`

**Comment by ekasetiawans** [comment]
hi @X-SLAYER we can use any other plugins with in this plugin as long that plugins doesn't require an Activity (android).
As you can see here:
https://github.com/flutter/plugins/blob/main/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraPlugin.java

that plugin require Activity to initialize the method channel. So, because this plugin is running the dart code inside a Service class, there is no possible to execute onAttachedToActivity method from camera plugin.

**Comment by X-SLAYER** [comment]
@ekasetiawans  thank you for the detailed response, in conclusion, I think If I want to use the camera with this package, the channel must be initialized in the `onAttachedToEngine`

**Comment by ekasetiawans** [comment]
@X-SLAYER correct, and we have to make sure the feature doesn't need Activity Context. If that feature need it, then we must initialize the method channel on `onAttachedToActivity` and that means it is not possible to use in background service.

**Comment by X-SLAYER** [comment]
@ekasetiawans got it thank you
