### ISSUE TITLE
Unable to run foreground service in iOS

### ISSUE THREAD

**Issue by junaidlodhi22** [ekasetiawans/flutter_background_service#137]
Hi
We are implementing this package and the package working fine in android. 
But the package is not working for iOS 
As we see in the code of the onStart method, the notification and setAsForeground are only for android in the recent update.
Is that the case? The foreground mode onStart will not work in iOS(with the notification)

**Comment by ekasetiawans** [comment]
@junaidlodhi22 foreground and background service are only available on Android. 

As we can see at https://github.com/ekasetiawans/flutter_background_service/blob/master/packages/flutter_background_service/example/lib/main.dart there are two arguments in IosConfiguration (onForeground and onBackground). the onForeground argument will be executed when app on foreground (its shown in screen) and the onBackground argument will be executed periodically by background fetch (or task scheduler) every 15-20 minutes. 

I know we are expect the same behavior in android and ios, but executing long running background task in ios is not possible because ios has no background service feature by OS.

**Comment by junaidlodhi22** [comment]
Right. Thank you for your response @ekasetiawans

**Comment by dangabdolfo** [comment]
Hi @ekasetiawans ,

Just to understand the behavior on IOS, when I close my app, the function called by the system is "onBackground" or there is the onFourground function which is called juste on time?

Thanks for your answer.
Regards, 
Daniel

**Comment by ekasetiawans** [comment]
@dangabdolfo on iOS, `onBackground` method will be invoked by background fetch or BGTaskScheduler. And `onForeground` method will be invoked by isolated dart vm when app is displayed on the screen.

**Comment by dangabdolfo** [comment]
Ok, however, the BGTaskScheduler call the onBackground method only if the app is on background and not killed by the user? 
Because with the example, the onBackground method is never called on my real device.
To test and verify it, I just change the current example to call an api rest and track when the call occur. And the api is called when the example app is in foreground but never when the app is in background or killed.

However the swift code seems good to me, and the task called by the BGTaskScheduler should be executed every 15 minutes.

Do you check the behavior recently?

**Comment by ekasetiawans** [comment]
Last time, I just checked using a simulator because my iphone was crashing. If you want to test using a simulator, you can run a sample project using xcode and simulate a background fetch.

**Comment by dangabdolfo** [comment]
Effectively I can make a test on simulator, but if in release mode and on a real device,  I get a different behavior...it's not good.

Have you a guide to debug the swift code present in the plugin?

**Comment by dangabdolfo** [comment]
Ok, I have found how to debug the pod and I begin my investigation. 
The good news is that if I launch in debug with the background fetch, effectively the exemple app is started from the background fetch callback.  I can observe the bellow sequence:
- In the first step the onBackground is called
- In the second step the onForeground is called.
However, if the onForeground embed a Dart timer, the call is not short...and the system kill the method. 
May be, on a background fetch event, the plugin should to call only on time the onBackground method?

What do you think about that?

**Comment by Lucesoft** [comment]
> Tamam, bölmede nasıl hata ayıklayacağımı buldum ve araştırmama başladım. İyi haber şu ki, arka plan getirme ile hata ayıklamayı başlatırsam ve bir arka plan getirme simülasyonu yaparsam, onBackground çağrılır. Yani, hepsi iyi görünüyor. Yardımlarınız için teşekkürler.

I have defined and assigned my onBackground method in IosConfiguration. This method is called periodically by the IOS every 15-20 minutes when the application is backgrounded or completely closed, isn't it? Did I understand correctly? Because it didn't seem to work at all to me, as a result of my actual device and emulator tests.

**Comment by Lucesoft** [comment]
I have defined and assigned my onBackground method in IosConfiguration. This method is called periodically by the IOS every 15-20 minutes when the application is backgrounded or completely closed, isn't it? Did I understand correctly? Because it didn't seem to work at all to me, as a result of my actual device and emulator tests.
