### ISSUE TITLE
AccountManager blocks forever when called inside a handler

### ISSUE THREAD

**Issue by Oberonc** [ekasetiawans/flutter_background_service#189]
I'm using the flutter package accountmanager for managing android accounts

inside the onStart method I have this line:
```
import 'package:accountmanager/accountmanager.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:permission_handler/permission_handler.dart';

void onStart(ServiceInstance service) async {
  bool isGranted = await Permission.contacts.isGranted;
  if (!isGranted) return;

  for (Account account in await AccountManager.getAccounts()) { // <- this line blocks forever
  }
}
```

Why does "AccountManager.getAccounts()" block ? how do I get/work with the accounts inside the background service ?

**Comment by ekasetiawans** [comment]
@Oberonc if you deep dive into https://github.com/ConteDevel/flutter-account-manager-plugin/blob/master/android/src/main/kotlin/com/contedevel/accountmanager/AccountManagerPlugin.kt
the `getAccounts()` method needs an activity not be null. Since this plugin is using Service, no Activities created. So you can't use that plugin in Service.

Closing this as external plugin issue.
