### ISSUE TITLE
Perform tasks like sending data to api throughout the day

### ISSUE THREAD

**Issue by marcelodev9** [ekasetiawans/flutter_background_service#192]
I made implementations for the service to perform tasks like calling an api to send some data. Everything works great even after closing the app (Android). Every time the process is performed, I store this information in the database as the time it took place after checking that the information through the service is working fine. However, I noticed that sometimes the service stopped performing the tasks for up to 1h, with differences until I use the device again.

**Comment by incloudss** [comment]
I have exactly the same problem. After about 40 min - 1 hour may foreground service stoips sending data to server. It turns out, that it is probably dozed. 
You can read about it here: 
https://stackoverflow.com/questions/52002533/does-service-startforeground-imply-wakelock
https://developer.android.com/training/monitoring-device-state/doze-standby

As a solution, it's said that the partial (cpu) lock needs to be acquired. Only then, the foreground service won't be put to sleep. I need to test yet this solution myself.

**Comment by ekasetiawans** [comment]
I have improved the background service on android, could you try to update the dependencies in your pubspec.yaml to flutter_background_service: ^2.2.1, let me know if this help you.
