### ISSUE TITLE
Background Service is not working when App is killed/closed or force terminated from recents.

### ISSUE THREAD

**Issue by wgroup07** [ekasetiawans/flutter_background_service#195]
I want to run background service in App . Actually Im working on Chat Application and require a background service to receive messages from chat server.
..................................
This case not working when App is closed.
service.setAsBackgroundService();
...................................
This case is working with a notification that is not required in my case.
service.setAsForegroundService();

**Comment by gamcho3** [comment]
same problem

**Comment by ekasetiawans** [comment]
Working with background service is very tricky, because it's has limitations start from Android Oreo and some android device manufacturer built their own custom android like MIUI by Xiaomi. So, we have to deal with those limitations. I suggest you to not use a background service for long running message receiver because it's not guaranteed, but you can use push notification service like FCM to receive notifications when your app is closed. Using FCM makes your app not consumes memory and battery because it's handled by google play service.

**Comment by Nightwelf** [comment]
> I want to run background service in App . Actually Im working on Chat Application and require a background service to receive messages from chat server. .................................. This case not working when App is closed. service.setAsBackgroundService(); ................................... This case is working with a notification that is not required in my case. service.setAsForegroundService();

hi! you find solution? help me

**Comment by ekasetiawans** [comment]
I just landed 2.3.0 with improvement especially for android service. Could you try it? @wgroup07

**Comment by sumanwebidigital** [comment]
Hi, I am interested in your plugin for iOS. Do plugins run a background service even when the app is killed/closed or force terminated?
