### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by zezo357** [ekasetiawans/flutter_background_service#208]
I had some questions I wanted to ask sorry if they are alot.

1- work manager vs your package (is it more than work even though the app is closed)

2- background task time limit ?

3- can I stop service (maybe I want to stop it for updating code by running in it with a new service)

4-the latest version of your package works in a  different isolate right?

5- how to make the customized notification since the recommended package has only predefined styles (not completely customizable)

**Comment by ekasetiawans** [comment]
1. On android, background service will running as long as it doesn't killed by system. Work manager will be running in a periodic task and in limited time
2. On android, there is no limit. But, the system might kill your service whenever needs more hardware resources for higher priority app. Note that, the highest priority is a foreground app that currently showing on the screen.
3. Ofcourse
4. Since first version, the dart code executed by service will running in a new isolate. But since 2.3.0 the service (on android) is not only in a isolate but in a different process. It's like you ran 2 apps in the same time. Every process will have their own memory management, when the main app (ui) closed by user, the service will be remains running.
5. You can use any notification plugin, follow the guidance for that plugin to customizing a notification.
