### ISSUE TITLE
Run Timer in the background

### ISSUE THREAD

**Issue by arpitjacob** [ekasetiawans/flutter_background_service#3]
Hi there just came across this plugin, would it be possible to run a timer in the background? The timer is activated from the app.

**Comment by ekasetiawans** [comment]
yes of course, I'll show you how

main.dart:

```dart

void main(){
   WidgetsFlutterBinding.ensureInitialized();
   FlutterBackgroundService.initialize(onServiceStart);
   runApp(MyApp());
}

```

service side:

```dart
onServiceStart(){
  WidgetsFlutterBinding.ensureInitialized();
  final service = FlutterBackgroundService();

  Timer timer;
  service.onDataReceived.listen((event){
     if (event["action"] == "startTimer"){
         timer = Timer.periodic(Duration(second: 1), (t){
                          print("tick");
                       });
     }

     if (event["action"] == "stopTimer" && timer != null){
        timer.cancel();
        print("timer has stopped");
     }
  });
}

```

ui side:

```dart
...
RaisedButton(child: Text("Start Timer"), onPressed: (){
  FlutterBackgroundService().sendData({"action": "startTimer"});
}),
RaisedButton(child: Text("Stop Timer"), onPressed: (){
  FlutterBackgroundService().sendData({"action": "stopTimer"});
}),
...
```

Keep in mind, the service can be killed by the system but the service will restart automatically after a few moments and the `onStartService` method will be executed all over again, so you have to save the state timer using `Shared Preferences` if needed.

**Comment by arpitjacob** [comment]
Thanks this is great, and the code looks pretty easy to implement.

**Comment by arpitjacob** [comment]
Sorry last question, this will work on an iOS/Android device even when the screen is turned off?

**Comment by ekasetiawans** [comment]
On Android, the service will try to run as long as possible and even if it is killed by the system, the service will be restarted by the alarm manager that I have set to wake up the service. For iOS I can't guarantee, because I'm not experienced in iOS development.

In the latest version, you can also choose whether the service will run in foreground mode or background mode, foreground mode is a service that uses notifications to keep the service running, while background mode does not. However, background mode has limitations since Android O, so this can affect the life of the service.

https://developer.android.com/about/versions/oreo/background

**Comment by zommerberg** [comment]
@ekasetiawans  How would it be possible to get the timer data and use it / show it somewhere? 
Would I need to create two different timers when starting a timer? 
- one as a Isolate that is running when the app is using the app and one as a background process that is running all the time?

This way we can show the data correct data when the user is using the app (the isolate timer). And when we turn off the screen the background timer would continue and we will be fine.

My questions are: 
- How do we get the data from the background timer when we open the app?
- Is the idea with the two timers even correct?
- Do we need to put the background timer in a isolate?

Thanks!

**Comment by ekasetiawans** [comment]
You can send data from a service to the UI in the same way by sending data from the UI to the service.

To receive messages from a service, you can use StreamBuilder with a stream from `FlutterBackgroundServi ce().onDataReceived`.

You don't need to run a timer on isolate, because this service itself is already running in isolate mode.

If you run the service in foreground mode, you can update the info in the notification by calling `service.setNotificationInfo` and make sure you call it from inside onStartService.


For additional information, the `FlutterBackgroundService` class is a singleton, so it's safe to call the constructor of this class multiple times because there will only be 1 instance in each isolate.

**Comment by zommerberg** [comment]
@ekasetiawans hello, thanks for the tips, I also explored the example you provided.
Two things that are not clear for me are:
- Is the foreground mode the new standard that should be used by default in the library, so far I don't see any downsides?
- How can I remove the notification? service.dispose() is not enough. Is there anything else I need to do?

**Comment by ekasetiawans** [comment]
Hi @zommerberg,

Look at this link to find out the foreground service on android
https://developer.android.com/guide/components/foreground-services

Since android oreo background service has been limited,
https://developer.android.com/about/versions/oreo/background. The background service cannot be used for a long time, therefore to overcome this we can use the foreground service, because there is no limit to the foreground service.

The notification that appears is required by the foreground service. You cannot remove it unless you end the foreground service mode to a background service by calling the command `service.setForegroundMode(false)` in the `onStartService()` method.

In foreground mode you can change the information in the notification with the command `service.setNotificationInfo` which must also be done in the `onStartService()` method.

You can issue commands to the service from the UI using `sendData` and capture those commands in the service by listening for `onDataReceived`.

**Comment by zommerberg** [comment]
@ekasetiawans  Thank you, my mistake, the text from the notification I was referring to was the app name, no wonder I did not see an option to change that.
I have tried removing the notification by calling service.setForegroundMode(false) but it did not work. I have used the example provided by the library and I tried to modify the `onStart` method so I can end the timer and remove the notification like that:
```
void onStart() {
  WidgetsFlutterBinding.ensureInitialized();
  final service = FlutterBackgroundService();
  // bring to foreground
  service.setForegroundMode(true);
  
  bool _isDisposed = false;
  service.onDataReceived.listen((event) {
    service.setForegroundMode(false);
    service.dispose();
    _isDisposed = true;
  });

  Timer.periodic(Duration(seconds: 1), (timer) {
    if (_isDisposed) {
      timer.cancel();
      return;
    }

    service.setNotificationInfo(
      title: "My App Service",
      content: "Updated at ${DateTime.now()}",
    );

    service.sendData(
      {"current_date": DateTime.now().toIso8601String()},
    );
  });
}
```
As you can see I am setting the foregroundMode to false and stopping the timer. Am I doing something wrong?

**Comment by zommerberg** [comment]
In the docs it says ```The notification cannot be
dismissed unless the service is either stopped or removed from the foreground.``` 
But I stop the service and remove it from the foreground (I even tried to reverse that part)

**Comment by zommerberg** [comment]
According to the docs
```
To remove the service from the foreground, call
stopForeground().
This method takes a boolean, which indicates whether to remove the status bar
notification as well. Note that the service continues to run.

If you stop the service while it's running in the foreground, its notification
is removed..```

currently when we invoke ```service.setForegroundMode(true/false);``` we trigger 
```
  void setForegroundMode(bool value) {
    if (Platform.isAndroid)
      _backgroundChannel.invokeMethod("setForegroundMode", {
        "value": value,
      });
  }
```
I am not sure where to fine the ```setForegroundMode``` method, but I assume it does not call ```stopForeground()``` when we remove the app from the foreground (when it is already running in the foregorund.)

**Comment by ekasetiawans** [comment]
@zommerberg thanks for feedback, I confirm that is a bug. I have create issue about it here #4.

**Comment by ekasetiawans** [comment]
closing this issue because it has been resolved, if there are still problems related to this issue please comment and I will reopen the issue.

**Comment by Nedimko123** [comment]
How would we do this now with all the updates?

**Comment by Roma9o** [comment]
Can you make a mini application with 2 start and stop buttons? I don't understand how this code works. To make the timer run in the background

**Comment by hafizijaz656** [comment]
Timer? timer;


    service.on('startTimer').listen((event) {
      timer = Timer.periodic(const Duration(seconds: 1), (t){
        print("tick");
      });
    });

    service.on('stopTimer').listen((event) {
      if(timer != null){
        timer!.cancel();
        print("timer has stopped");
      }

    });


service.invoke("stopTimer");

 service.invoke("startTimer");
