### ISSUE TITLE
crash when stopService

### ISSUE THREAD

**Issue by shingohu** [ekasetiawans/flutter_background_service#410]
E/AndroidRuntime( 1753): java.lang.RuntimeException: Unable to stop service id.flutter.flutter_background_service.BackgroundService@378385c: kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized
E/AndroidRuntime( 1753): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
E/AndroidRuntime( 1753): 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
E/AndroidRuntime( 1753): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
E/AndroidRuntime( 1753): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 1753): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime( 1753): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime( 1753): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/AndroidRuntime( 1753): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1753): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/AndroidRuntime( 1753): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/AndroidRuntime( 1753): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property channel has not been initialized
E/AndroidRuntime( 1753): 	at fl.camera.FlCameraPlugin.onDetachedFromEngine(FlCameraPlugin.kt:35)
E/AndroidRuntime( 1753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
E/AndroidRuntime( 1753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime( 1753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime( 1753): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
E/AndroidRuntime( 1753): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:467)
E/AndroidRuntime( 1753): 	at id.flutter.flutter_background_service.BackgroundService.onDestroy(BackgroundService.java:121)
E/AndroidRuntime( 1753): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)

**Comment by Alfaizkhan** [comment]
Same issue here.

`I/flutter (27215): Stopping foreground service ...
D/FlutterWebRTCPlugin(27215): Stopping the audio manager...
D/AndroidRuntime(27215): Shutting down VM
E/AndroidRuntime(27215): FATAL EXCEPTION: main
E/AndroidRuntime(27215): Process: com.cerashealth.imhomev2, PID: 27215
E/AndroidRuntime(27215): java.lang.RuntimeException: Unable to stop service id.flutter.flutter_background_service.BackgroundService@4f458c5: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(27215): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4871)
E/AndroidRuntime(27215): 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
E/AndroidRuntime(27215): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2297)
E/AndroidRuntime(27215): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27215): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(27215): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(27215): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(27215): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27215): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(27215): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(27215): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
E/AndroidRuntime(27215): 	at co.tryterra.terra_flutter_bridge.TerraFlutterPlugin.onDetachedFromEngine(TerraFlutterPlugin.java:463)
E/AndroidRuntime(27215): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:272)
E/AndroidRuntime(27215): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:282)
E/AndroidRuntime(27215): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:290)
E/AndroidRuntime(27215): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:123)
E/AndroidRuntime(27215): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:460)
E/AndroidRuntime(27215): 	at id.flutter.flutter_background_service.BackgroundService.onDestroy(BackgroundService.java:121)
E/AndroidRuntime(27215): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4851)
E/AndroidRuntime(27215): 	... 9 more
W/FirebaseCrashlytics(27215): Unable to read App Quality Sessions session id.
I/Process (27215): Sending signal. PID: 27215 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"631","method":"resume","params":{"isolateId":"isolates/8214134477214619"}}
the Dart compiler exited unexpectedly.
`

**Comment by Tahateber95** [comment]
@shingohu
 you need to check whether the service is running or not.

`await flutterBackgroundService.isRunning()`

**Comment by shingohu** [comment]
> @shingohu you need to check whether the service is running or not before you stop it.
> 
> `await flutterBackgroundService.isRunning()`

Problems with the fl_camera plugin
